### ISSUE TITLE
What is the meaning of  number of games

### ISSUE THREAD

**Issue by JBMing** [tambetm/matlab2048#2]
When i run the code,code will produce 4 figure in one pic denoting the condition of playing game,
One of 4 figures in pic is "Number of games".
I don;t know its meaning.
Can u explain it?

**Comment by tambetm** [comment]
The plots are updated after every 10000 training iterations (roughly equivalent to moves in game). The number shows how many games the agent was able to play during this 10000 iterations. One would expect the number of games to decrease, because once the agent is smarter it can stay in game longer. It's better to calculate statistics after certain number of training iterations, rather than certain number of games played, because games can have different length and number of training episodes is the best approximate to in what phase the agent is in learning.

**Comment by tambetm** [comment]
BTW, I never got this code really learning.
